
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS WORKGROUP;

CREATE TABLE WORKGROUP (
  ID         INT PRIMARY KEY NOT NULL,
  NAME       VARCHAR(80) NOT NULL
);

INSERT INTO WORKGROUP (ID, NAME) VALUES
  (1, 'First group'),
  (2, 'Second group'),
  (3, 'Third group');
  
CREATE TABLE EMPLOYEE (
  ID          INT    PRIMARY KEY NOT NULL,
  FIRST_NAME  VARCHAR(40) NOT NULL,
  LAST_NAME   VARCHAR(40) NOT NULL,
  BIRTH_DATE  DATE DEFAULT NULL,
  GROUP_ID    INT  
);
